/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-south-1",
    "aws_appsync_graphqlEndpoint": "https://gexdptppx5fqtdsfqpsolml6km.appsync-api.ap-south-1.amazonaws.com/graphql",
    "aws_appsync_region": "ap-south-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-42d67n26cfdynjfc2af5hdv224",
    "aws_cognito_identity_pool_id": "ap-south-1:0ed6e93b-ddbe-469d-aa37-fb5c8f282369",
    "aws_cognito_region": "ap-south-1",
    "aws_user_pools_id": "ap-south-1_ChJqGIzjA",
    "aws_user_pools_web_client_id": "33n4c0rtij2th74dleq2sndte",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "postagram69f88c79076c42dd9bb67fd86c970d9b161114-devss",
    "aws_user_files_s3_bucket_region": "ap-south-1"
};


export default awsmobile;
